id: P98EBDEE4
initial_creation_type: input
source_metadata:
  title: Medicine Buddha
  language: en
  description: 'Texts related to the Medicine Buddha or Bhaiṣajya Guru (sman bla),
    Lord of Physicians:'
  volume:
    2b3e5220b3cb4300b6b5066630fedbad:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    bd3761ba7c0b46ebb5f302bd1bb06028:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    3ecf0130e5414ffcaaf6e4a8ce917755:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Sādhanas
    cfc32c5f01e14cd9b6d8944206009c84:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Sādhanas
created_at: '2022-03-01T04:39:26.198158'
last_modified_at: '2022-03-01T04:39:26.198164'
